### ISSUE TITLE
dependency failed to start: container hellodata-keycloak-1 is unhealthy

### ISSUE THREAD

**Issue by gangerang** [kanton-bern/hellodata-be#21]
Tried to run via docker desktop on two sepereate windows 10 devices with WSL2. Each time receive "dependency failed to start: container hellodata-keycloak-1 is unhealthy" error. Have tired multiple removals and re-installs with same result.

**Comment by SiddiqueAhmad** [comment]
This sql file is not valid for container start-up 

https://github.com/kanton-bern/hellodata-be/blob/main/hello-data-deployment%2Fdocker-compose%2Fbase%2Fpostgres%2Finit-scripts%2F3_default_data_domain_dwh_udm_data.sql

**Comment by SiddiqueAhmad** [comment]
I was able to run in pieces but it was restarting for some reason

**Comment by nschmid** [comment]
"container hellodata-keycloak-1 is unhealthy" error sounds like the keycloak container can't start. I experienced that sometimes when the setup was missing something.

Did you setup your windows box accordingly? https://github.com/kanton-bern/hellodata-be/blob/main/hello-data-deployment/docker-compose/README.md#prepare-environment ?

Sometimes this happens when `*.docker.internal` is not setup correctly in your **etc/hosts** file.

**Comment by sspaeti** [comment]
One small addition @gangerang, did you download the latest [Docker Desktop](https://www.docker.com/products/docker-desktop/)? We had two incidents on Mac and Windows, where downloading the latest Docker Desktop solved issues. And you must add the settings on Docker Desktop settings as nschmid mentioned: 
- Add `*.docker.internal` to the host's `/etc/hosts` file. (Password required). Lets you resolve *.docker.internal DNS names from both the host and your containers.

And how much RAM/CPU did you dedicate to Docker Desktop?

**Comment by SiddiqueAhmad** [comment]
Thanks pulled latest, also set the proper `*.docker.internal `

I have given 10GB ram, and 8 cores and on latest docker desktop on mac, but it keep restarting portal api, monitoring sbt, dbt docs and few others

**Comment by gangerang** [comment]
Finally got it working! I think possible a combination of a few things. Pulled most recent code. Manually edited /etc/hosts to add the 127.0.0.1  host.docker.internal line, the setting in Docker Desktop for WSL2 doesn't seem to add it correctly. Finally I had to stop an existing postgres server I was running locally on the default port 5432 as I think that was then causing Superset to fail.

**Comment by sspaeti** [comment]
That is invaluable feedback, thanks for the effort. I'll add these two points (turning off Postgres locally and checking the host file to be added correctly) to the readme on Monday.

**Comment by sspaeti** [comment]
I updated the [docker-compose Readme](https://github.com/kanton-bern/hellodata-be/blob/develop/hello-data-deployment/docker-compose/README.md#prepare-environment) to make sure others do not run into the same error. @gangerang let me know if that is clear and correct. I'm closing the issue until then.
