### ISSUE TITLE
Failed to start on MacOS with Docker (keycloak problem)

### ISSUE THREAD

**Issue by bbonnin** [kanton-bern/hellodata-be#25]
Hello,

I'm trying to start the platform on a MacOS M1 using Docker (docker-compose up -d), and I get the following error:
```
 > [keycloak ubi-micro-build 3/3] RUN dnf install --installroot /mnt/rootfs curl --releasever 9 --setopt install_weak_deps=false --nodocs -y &&     dnf --installroot /mnt/rootfs clean all &&     rpm --root /mnt/rootfs -e --nodeps setup:
0.967 Updating Subscription Management repositories.
0.967 Unable to read consumer identity
0.968
0.968 This system is not registered with an entitlement server. You can use subscription-manager to register.
0.968
2.172 Red Hat Universal Base Image 9 (RPMs) - BaseOS  0.0  B/s |   0  B     00:00
2.172 Errors during downloading metadata for repository 'ubi-9-baseos-rpms':
2.172   - Curl error (60): SSL peer certificate or SSH remote key was not OK for https://cdn-ubi.redhat.com/content/public/ubi/dist/ubi9/9/aarch64/baseos/os/repodata/repomd.xml [SSL certificate problem: self-signed certificate in certificate chain]
2.179 Error: Failed to download metadata for repo 'ubi-9-baseos-rpms': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried
------
failed to solve: process "/bin/sh -c dnf install --installroot /mnt/rootfs curl --releasever 9 --setopt install_weak_deps=false --nodocs -y &&     dnf --installroot /mnt/rootfs clean all &&     rpm --root /mnt/rootfs -e --nodeps setup" did not complete successfully: exit code: 1
```

As requested, I have updated the Docker Deskopt config and my /etc/hosts file. My connection on Internet is OK.

Any ideas ? Thanks !

**Comment by sspaeti** [comment]
Thanks for the report @bbonnin. We think it's not related to HelloDATA platform.

Nevertheless, could you check if you can access https://cdn-ubi.redhat.com/content/public/ubi/dist/ubi9/9/aarch64/baseos/os/repodata/repomd.xml with your browser?

It seems you might either have a general problem to get to the internet (as this link is accessible) or that your docker container cannot connect to the outside world.

If it's the latter, and you can access the link with your browser, you could try to use `--insecure` or `--sslverify=false`

here some related links
- https://keycloak.discourse.group/t/keycloak-21-docker-missing-microdnf/20464/6
- https://github.com/RedHatQE/ocp-gitlab-runner/issues/19

Let us know how that goes.

**Comment by sspaeti** [comment]
@bbonnin Did above solve the issue? If not, please feel free to add some more logs or error we can help with. Until then, I will close the issue; Happy to re-open if not solved.

**Comment by bbonnin** [comment]
Hello,
Sorry I forgot to close the issue :( 
I had a problem with Docker, I reinstalled all the stuffs and finally, it works !
Thank you for your suuport for this great project !
