### ISSUE TITLE
Can't configure PORTS

### ISSUE THREAD

**Issue by thebigleboo** [kanton-bern/hellodata-be#30]
I want to configure on which ports the app will start. Mainly the DB (5432 is already taken) and the main PORT (8080 is also taken). 

How can I ?

**Comment by nschmid** [comment]
Hi @thebigleboo 

Thanks for your question. I think a simple solution would be to go through the docker-compose setup and change the ports accordingly: https://github.com/kanton-bern/hellodata-be/tree/develop/hello-data-deployment/docker-compose

Just change the ":5432" and ":8080" references according to your needs.

**Comment by thebigleboo** [comment]
Thank you !!
