### ISSUE TITLE
Container not found : bedag/hello-data-dc-portal

### ISSUE THREAD

**Issue by nitish2507** [kanton-bern/hellodata-be#46]
Error response from daemon: pull access denied for bedag/hello-data-dc-portal, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

**Comment by nschmid** [comment]
Hi @nitish2507 thanks for your message. I'll have a look at it...

**Comment by nschmid** [comment]
Hi @nitish2507 
Can you try again?

**Comment by nitish2507** [comment]
Hi @nschmid It works fine now :) Was able to run all the containers (35 in total).

The portal seems to be broken though, this is what comes up. 

<img width="1437" alt="image" src="https://github.com/kanton-bern/hellodata-be/assets/20018328/53f395cd-b92e-49fa-b1e2-83da17a9ea48">

**Comment by nitish2507** [comment]
I will close this issue as solved and open a new one for you to track. Thanks
