### ISSUE TITLE
Cannot run HelloDATA on Ubuntu, api-1 and ui-1 error

### ISSUE THREAD

**Issue by stephan-meier** [kanton-bern/hellodata-be#54]
✔ Container hellodata-airflow-worker-1                                   Started                                         207.5s 
 ✔ Container hellodata-airflow-triggerer-1                                Star...                                         210.3s 
 ✔ Container hellodata-airflow-webserver-1                                Star...                                         209.9s 
 ✔ Container hellodata-hello-data-superset-sidecar-default-data-domain-1  Started                                         290.9s 
 ✔ Container hellodata-hello-data-superset-sidecar-extra-data-domain-1    Started                                         348.4s 
 ✔ Container hellodata-hello-data-airflow-sidecar-1                       Started                                         212.4s 
 ✘ Container hellodata-hello-data-portal-api-1                            Error                                           522.4s 
 ✔ Container hellodata-hello-data-portal-sidecar-1                        Started                                         365.5s 
 ⠹ Container hellodata-hello-data-portal-ui-1                             C...                                            522.3s 
dependency failed to start: container hellodata-hello-data-portal-api-1 is unhealthy

Docker version: Docker version 25.0.4, build 1a576c5
Ubuntu version: Ubuntu 22.04.4 LTS, fresh install on VMWare, 12GB RAM, 60GB Disk

Any ideas??

Best regards
Stephan

**Comment by wieczorslawo** [comment]
Hi Stephan. Can you provide us with logs from the hellodata-hello-data-portal-api-1 container?

**Comment by stephan-meier** [comment]
Sorry for the delay, holidays...

[_hellodata-hello-data-portal-api-1_logs.txt](https://github.com/kanton-bern/hellodata-be/files/14882954/_hellodata-hello-data-portal-api-1_logs.txt)

![screenshot_hellodata](https://github.com/kanton-bern/hellodata-be/assets/1374165/78f2798d-dadf-41bb-97e0-4594b81ff9cf)

**Comment by wieczorslawo** [comment]
Hi Stephan, could you pull as we made some adjustments since you started? Please try from scratch with the following commands:
docker-compose down --volumes
git pull
docker-compose up -d

**Comment by stephan-meier** [comment]
Thanks for the input, now superset seems to be broken?

![screenshot_hellodata_240408_01](https://github.com/kanton-bern/hellodata-be/assets/1374165/c24be3aa-bbba-48e4-b271-5866ae0767aa)

**Comment by wieczorslawo** [comment]
Hi Stephan. Thank you for the info. Did you do a docker-compose pull? It's also recommended to update images (I forgot to write that in my previous message, sorry). If so please provide us with superset-init-default-data-domain container logs.

**Comment by stephan-meier** [comment]
There are no logs available, the superset (and airflow) containers are never created. The script crashes after hellodata_hello-data-dbt-docs-sidecar_1.

![screenshot_hellodata_240409_01](https://github.com/kanton-bern/hellodata-be/assets/1374165/7c95444e-cae6-40ef-884c-3e921496a973)

**Comment by wieczorslawo** [comment]
Hi Stephan. We couldn't reproduce this error on Ubuntu 22.04. Please confirm if you followed the instructions from here:
https://github.com/kanton-bern/hellodata-be/blob/develop/hello-data-deployment/docker-compose/README.md
