### ISSUE TITLE
Portal UI seems broken on intial deployment.

### ISSUE THREAD

**Issue by nitish2507** [kanton-bern/hellodata-be#57]
All the 35 containers are running fine.
Upon accessing the portal UI, this is what we see.

<img width="1440" alt="image" src="https://github.com/kanton-bern/hellodata-be/assets/20018328/6c2ac33f-83ea-4a5f-b136-61cd506bbb22">

**Comment by wieczorslawo** [comment]
Hi @nitish2507, please provide us with the console log from your browser. Also the browser type and version, OS would be helpful.
Thanks

**Comment by nschmid** [comment]
Hi @nitish2507 
Is the portal-api (the backend) up and running?
In the footer you get "undefined" version... which indicates that the version can not be fetched from the backend...

**Comment by nitish2507** [comment]
Hi @nschmid and @wieczorslawo - Let me check and come back.

**Comment by wieczorslawo** [comment]
Hi. We added some changes to the docker compose. Please update your repo and run docker-compose pull.
Regards
Slawo

**Comment by wieczorslawo** [comment]
Also please don't forget to review the README.md file in the docker-compose directory

**Comment by bedag-bad** [comment]
Closed for housekeeping
