### ISSUE TITLE
Link in documentation to Roles and authorization concept doesn't work.

### ISSUE THREAD

**Issue by KonaMan1** [kanton-bern/hellodata-be#82]
In the documentation https://github.com/kanton-bern/hellodata-be/blob/develop/docs/docs/architecture/infrastructure.md, the link mentioned link in the title doesn't work

**Comment by sspaeti** [comment]
@KonaMan1 Thank you so much for the report. It is fixed now. The broken link to "Roles and authorization concept" should have pointed to https://kanton-bern.github.io/hellodata-be/manuals/role-authorization-concept/, which it does now.
